version: '3'
services:
  recognizer:
    container_name: recognizer-service-dotnet
    build: Recognizer/
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: Development
